### ISSUE TITLE
CPU Panic when boot ,with IONVMeFamily,IOStorageFamily

### ISSUE THREAD

**Issue by notOops** [H3C4T0M8/Hackintosh-ASUS-Rog-Strix-B450i-Gaming-OpenCore#1]
I have the same motherboard ,It runs well most of the time, but sometimes it reboots a few times when boot.
It shows CPU Painc with IONVMeFamily, IOStorageFamily in the crash log:
`Panic(CPU 3, time 6733784368): NMIPI for spinlock acquisition timeout, spinlock: 0xffffffa3ffc84d80, spinlock owner: 0xffffff9a68c21b30, current_thread: 0xffffff9a68c21b30, spinlock_owner_cpu: 0x3
RAX: 0x00000009a64c5ea6, RBX: 0xffffff9f33820600, RCX: 0x00000009a64c5ea6, RDX: 0x0000000000000001
RSP: 0xffffffacd825b468, RBP: 0xffffffacd825b4b0, RSI: 0x00000009a64c5ea6, RDI: 0xffffffa3ff4b2600
R8:  0x000000000000ffff, R9:  0x0000000100cf0002, R10: 0x0000000000000000, R11: 0x0000000000000000
R12: 0x0000000000000008, R13: 0x0000000000000000, R14: 0xffffffa3ff4b2600, R15: 0xffffff9f338a54b0
RFL: 0x0000000000000286, RIP: 0xffffff80147d9345, CS:  0x0000000000000008, SS:  0x0000000000000010
Panicked task 0xffffff959acbfdf0: 3 threads: pid 93: biomed
Backtrace (CPU 3), panicked thread: 0xffffff9a68c21b30, Frame : Return Address
0xffffff8064a25f80 : 0xffffff8012147a47 mach_kernel : _interrupt + 0xd7
0xffffff8064a25fe0 : 0xffffff8011f85a7a mach_kernel : _hndl_allintrs + 0x9a
0xffffffacd825b4b0 : 0xffffff80147dd936 com.apple.iokit.IONVMeFamily : __ZN24IONVMeBlockStorageDevice16doAsyncReadWriteEP18IOMemoryDescriptoryyP19IOStorageAttributesP19IOStorageCompletion + 0x3ee
0xffffffacd825b590 : 0xffffff8014b921ed com.apple.iokit.IOStorageFamily : __ZN20IOBlockStorageDriver14executeRequestEyP18IOMemoryDescriptorP19IOStorageAttributesP19IOStorageCompletionPNS_7ContextE + 0x129
0xffffffacd825b600 : 0xffffff8014b94e07 com.apple.iokit.IOStorageFamily : __ZN20IOBlockStorageDriver14prepareRequestEyP18IOMemoryDescriptorP19IOStorageAttributesP19IOStorageCompletion + 0x21b
0xffffffacd825b6b0 : 0xffffff8014b9b8c2 com.apple.iokit.IOStorageFamily : __ZL11dkreadwritePv9dkrtype_t + 0x61c
0xffffffacd825b760 : 0xffffff801221fdc4 mach_kernel : _spec_strategy + 0x454
0xffffffacd825b7c0 : 0xffffff80121b6c75 mach_kernel : _buf_strategy + 0x1f5
0xffffffacd825b860 : 0xffffff80150ef23f com.apple.filesystems.apfs : _apfs_vnop_strategy + 0x731
0xffffffacd825b950 : 0xffffff80121c0711 mach_kernel : _cluster_pageout_ext + 0x1011
0xffffffacd825baa0 : 0xffffff80121c6ad0 mach_kernel : _cluster_read_ext + 0xe80
0xffffffacd825bc60 : 0xffffff80121c5dc4 mach_kernel : _cluster_read_ext + 0x174
0xffffffacd825bcd0 : 0xffffff8015106041 com.apple.filesystems.apfs : _apfs_vnop_read + 0x50a
0xffffffacd825bd90 : 0xffffff80122056b0 mach_kernel : _vn_close + 0x2c0
0xffffffacd825be00 : 0xffffff801220442d mach_kernel : _utf8_normalizeOptCaseFoldAndMatchSubstring + 0x58d
0xffffffacd825be60 : 0xffffff801254a85c mach_kernel : _read_nocancel + 0x23c
0xffffffacd825bec0 : 0xffffff801254ab33 mach_kernel : _pread_nocancel + 0x103
0xffffffacd825bf40 : 0xffffff801265545b mach_kernel : _unix_syscall64 + 0x1db
0xffffffacd825bfa0 : 0xffffff8011f85d96 mach_kernel : _hndl_unix_scall64 + 0x16
      Kernel Extensions in backtrace:
         com.apple.iokit.IOStorageFamily(2.1)[62F2C392-9547-33CB-8E12-6F77B7B052AF]@0xffffff8014b8c000->0xffffff8014ba2fff
         com.apple.filesystems.apfs(2142.81.1)[ABBD14C1-8418-36B8-B9E3-99E28D31FE7E]@0xffffff80150a6000->0xffffff8015235fff
            dependency: com.apple.driver.AppleEFINVRAM(2.1)[A76C0078-40F9-34AA-B71E-D3D05EFFFE29]@0xffffff80133f0000->0xffffff80133f9fff
            dependency: com.apple.driver.AppleEffaceableStorage(1.0)[EEB614DE-F259-3310-8E43-F841B50CCF6A]@0xffffff8013406000->0xffffff801340bfff
            dependency: com.apple.iokit.CoreAnalyticsFamily(1)[BF4BE411-8D61-3123-AEA0-88671FB17B81]@0xffffff8013926000->0xffffff801392ffff
            dependency: com.apple.iokit.IOStorageFamily(2.1)[62F2C392-9547-33CB-8E12-6F77B7B052AF]@0xffffff8014b8c000->0xffffff8014ba2fff
            dependency: com.apple.kec.corecrypto(12.0)[CADEE2DB-DF62-3630-A9F9-BC8B75D43579]@0xffffff801527b000->0xffffff80152f3fff
            dependency: com.apple.security.AppleImage4(5.0.0)[712FD39E-9705-3C94-9F0D-174AF4EE307C]@0xffffff8013491000->0xffffff80134affff
         com.apple.iokit.IONVMeFamily(2.1)[C334C31D-7F48-3BE5-A0A4-108210D621D0]@0xffffff80147c1000->0xffffff80147edfff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[DB38BB35-D38C-3110-9B53-0D2927F702CF]@0xffffff80135c5000->0xffffff80135f3fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[802B9CA4-B851-396E-8DA4-B30E751EC48F]@0xffffff8014a59000->0xffffff8014a88fff
            dependency: com.apple.iokit.IOReportFamily(47)[D8F664BF-70CB-3596-A4D5-35E72EBC36EE]@0xffffff8014a9a000->0xffffff8014a9cfff
            dependency: com.apple.iokit.IOStorageFamily(2.1)[62F2C392-9547-33CB-8E12-6F77B7B052AF]@0xffffff8014b8c000->0xffffff8014ba2fff
      Kernel Extensions in backtrace:
         com.apple.iokit.IONVMeFamily(2.1)[C334C31D-7F48-3BE5-A0A4-108210D621D0]@0xffffff80147c1000->0xffffff80147edfff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[DB38BB35-D38C-3110-9B53-0D2927F702CF]@0xffffff80135c5000->0xffffff80135f3fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[802B9CA4-B851-396E-8DA4-B30E751EC48F]@0xffffff8014a59000->0xffffff8014a88fff
            dependency: com.apple.iokit.IOReportFamily(47)[D8F664BF-70CB-3596-A4D5-35E72EBC36EE]@0xffffff8014a9a000->0xffffff8014a9cfff
            dependency: com.apple.iokit.IOStorageFamily(2.1)[62F2C392-9547-33CB-8E12-6F77B7B052AF]@0xffffff8014b8c000->0xffffff8014ba2fff

Process name corresponding to current thread (0xffffff9a68c21b30): biomed
Boot args: -v keepsyms=1 debug=0x100 npci=0x2000 alcid=5 agdpmod=pikera 

Mac OS version:
22D68

Kernel version:
Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64
Kernel UUID: 10E5D254-4A37-3A2A-B560-E6956A093ADE
roots installed: 0
KernelCache slide: 0x0000000011c00000
KernelCache base:  0xffffff8011e00000
Kernel slide:      0x0000000011cdc000
Kernel text base:  0xffffff8011edc000
__HIB  text base: 0xffffff8011d00000
System model name: MacPro7,1 (Mac-27AD2F918AE68F61)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 7115490861
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x00000001a8ea6891
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x0000000e093176ce 0x0000000000000000
Compressor Info: 0% of compressed pages limit (OK) and 0% of segments limit (OK) with 0 swapfiles and OK swap space
Zone info:
  Zone map: 0xffffff8a65bc4000 - 0xffffffaa65bc4000
  . PGZ   : 0xffffff8a65bc4000 - 0xffffff8a67bc5000
  . VM    : 0xffffff8a67bc5000 - 0xffffff8f343c4000
  . RO    : 0xffffff8f343c4000 - 0xffffff90cdbc4000
  . GEN0  : 0xffffff90cdbc4000 - 0xffffff959a3c4000
  . GEN1  : 0xffffff959a3c4000 - 0xffffff9a66bc4000
  . GEN2  : 0xffffff9a66bc4000 - 0xffffff9f333c4000
  . GEN3  : 0xffffff9f333c4000 - 0xffffffa3ffbc4000
  . DATA  : 0xffffffa3ffbc4000 - 0xffffffaa65bc4000
  Metadata: 0xffffffaa91dd6000 - 0xffffffaab1dd6000
  Bitmaps : 0xffffffaab1dd6000 - 0xffffffaab7dd6000

panic(cpu 10 caller 0x<ptr>): Spinlock[0xffffffa3ffc84d80] timeout after 430756627 ticks ;lock owner thread=0xffffff9a68c21b30, current_thread: 0xffffff9a690d8b30, lock owner active on CPU 3, start time: 84298326476, now: 84729083103, timeout: 430737432 @locks_i386.c:487
Panicked task 0xffffff959a48d9d8: 5 threads: pid 136: revisiond
Backtrace (CPU 10), panicked thread: 0xffffff9a690d8b30, Frame : Return Address
0xffffffacd806eff0 : 0xffffff8011feb38d mach_kernel : _handle_debugger_trap + 0x4ad
0xffffffacd806f040 : 0xffffff8012158ed6 mach_kernel : _kdp_i386_trap + 0x116
0xffffffacd806f080 : 0xffffff8012148120 mach_kernel : _kernel_trap + 0x3e0
0xffffffacd806f0d0 : 0xffffff8011f85951 mach_kernel : _return_from_trap + 0xc1
0xffffffacd806f0f0 : 0xffffff8011feb66d mach_kernel : _DebuggerTrapWithState + 0x5d
0xffffffacd806f1e0 : 0xffffff8011fead19 mach_kernel : _panic_trap_to_debugger + 0x1a9
0xffffffacd806f240 : 0xffffff80127e072b mach_kernel : _panic + 0x84
0xffffffacd806f330 : 0xffffff801213c56f mach_kernel : _lck_spin_lock_grp + 0xbf
0xffffffacd806f390 : 0xffffff8012003a25 mach_kernel : _lck_spinlock_timeout_set_orig_ctid + 0x375
0xffffffacd806f410 : 0xffffff801213c585 mach_kernel : _IOSimpleLockLock + 0x15
0xffffffacd806f430 : 0xffffff80147d06cd com.apple.iokit.IONVMeFamily : __ZN16IONVMeController13SubmitCommandEP24AppleNVMeSubmissionQueueP16AppleNVMeRequest + 0x1f
0xffffffacd806f460 : 0xffffff80147ce7ad com.apple.iokit.IONVMeFamily : __ZN16IONVMeController18ProcessNVMeRequestEP16AppleNVMeRequestb + 0x1d3
0xffffffacd806f4b0 : 0xffffff80147dd936 com.apple.iokit.IONVMeFamily : __ZN24IONVMeBlockStorageDevice16doAsyncReadWriteEP18IOMemoryDescriptoryyP19IOStorageAttributesP19IOStorageCompletion + 0x3ee
0xffffffacd806f590 : 0xffffff8014b921ed com.apple.iokit.IOStorageFamily : __ZN20IOBlockStorageDriver14executeReq`

Is this an SSD related issue? I tried using NvmeFix.kexts, but nothing works, and it boot slower.

I have also tried pci built-in ,not works.
SSD is SN 570 in the second SSD slot, motherboard PCI-E can only use 3.0x8 GPU+3.0x4 SSD +3.0x4 SSD.

**Comment by H3C4T0M8** [comment]
Wait some minutes... what macOS you use? I will give you my last EFI in some minutes. I think I know what happens.

**Comment by H3C4T0M8** [comment]
What CPU you use?

**Comment by H3C4T0M8** [comment]
I use a 12 Core CPU....so you need to change the core number from 4 Patches !!!!

[ASUS B450 i OC 0.9.0 EFI .zip](https://github.com/H3C4T0M8/Hackintosh-ASUS-Rog-Strix-B450i-Gaming-OpenCore/files/10892118/ASUS.B450.i.OC.0.9.0.EFI.zip)

INFOS here to see : https://github.com/AMD-OSX/AMD_Vanilla

**Comment by notOops** [comment]
> 
R5 5600X with macOS 13.2.1 OpenCore 0.8.9 ,CPU patches has been changed(0.8.9 already 4 ).
I will try 0.9.0 latrer

**Comment by notOops** [comment]
Another problem is that the second ssd can‘t be erased and repartitioned when install , I used “hdutil” command in terminal to get it and successfully install .
Now the only problem is that I might needs to 2 or 3 times can I boot successfully.
Could be the motherboard's second SSD slot own defect ？And may need to add some ACPI patches?

**Comment by H3C4T0M8** [comment]
Hmm. You have try boot with only one ssd? I will ask someone, and send him a link to the comments here. I think he know more than me.

**Comment by notOops** [comment]
> Hmm. You have try boot with only one ssd? I will ask someone, and send him a link to the comments here. I think he know more than me.

There was no problem when I use one SSD before,but it's macOS 12 long times ago.Now I have tried 0.9.0 ,not matter.The motherboard change ssd is much cost time ,I would like to try something else,then changge ssd slot .

**Comment by H3C4T0M8** [comment]
I ask the guy. He told me that OC in the last versions make problems, too.

**Comment by notOops** [comment]
I tried Only 1 ssd，the same problem.But I enable resizeablebar in bios，and set the quirks “resize gpubars” to 0,and delete boot-args “npci=0x2000”,now cpu panic less than before.

**Comment by H3C4T0M8** [comment]
You tried already a older OC version ? I don't got problems with my system. My system don't get boot issue.

**Comment by Monodiess** [comment]
> You tried already a older OC version ? I don't got problems with my system. My system don't get boot issue.

not yet,later maybe

**Comment by notOops** [comment]
> You tried already a older OC version ? I don't got problems with my system. My system don't get boot issue.
I tried 0.86 and macOS 12 the same problem .

**Comment by H3C4T0M8** [comment]
Hmm. Than I really don't know if the ssd or nvme the problem. I never got problems with my system. But I know that Asus have 2 different b450 I Mainboards... they have a Chinese version, or so too. Have read it at other GitHub.
